name: 'Base Setup'
description: "Installs core modules, download and enables required contrib modules, and applies basic site configuration."
type: 'drupal-recipe'

recipes:
  - core/recipes/administrator_role
  - core/recipes/content_editor_role
  - core/recipes/document_media_type
  - core/recipes/image_media_type
  - core/recipes/remote_video_media_type
  - core/recipes/basic_html_format_editor
  - core/recipes/full_html_format_editor

install:
  # Core modules
  - block_content
  - breakpoint
  - ckeditor5
  - config
  - content_moderation
  - workflows
  - contextual
  - menu_link_content
  - field_ui
  - inline_form_errors
  - layout_builder
  - layout_discovery
  - media
  - media_library
  - menu_ui
  - phpass
  - path
  - responsive_image
  - search
  - taxonomy
  - editor
  - views
  - views_ui
  - datetime
  - datetime_range
  - file
  - image
  - link
  - options
  - telephone
  # Contrib modules
  - address
  - backup_migrate
  - better_exposed_filters
  - better_social_sharing_buttons
  - block_field
  - coffee
  - config_ignore
  - config_split
  - content_lock
  - csp
  - editor_advanced_link
  - editoria11y
  - field_group
  - flood_control
  - focal_point
  - http_cache_control
  - honeypot
  - image_widget_crop
  - inline_entity_form
  - link_attributes
  - linkit
  - login_emailusername
  - mailsystem
  - masquerade
  - media_library_edit
  - media_library_form_element
  - memcache
  - memcache_admin
  - menu_admin_per_menu
  - menu_item_extras
  - menu_link_attributes
  - metatag
  - paragraphs
  - paragraphs_report
  - password_policy
  - pathauto
  - quick_node_clone
  - rabbit_hole
  - redirect
  - redirect_404
  - remove_http_headers
  - robotstxt
  - sam
  - scheduler
  - schema_metatag
  - seckit
  - simple_sitemap
  - stage_file_proxy
  - svg_image
  - tagify
  - token_filter
  - twig_tweak
  - trash
  - view_unpublished
  - views_infinite_scroll
  - webp
  - weight
