name: 'Base Setup'
description: "Installs core modules, download and enables required contrib modules, and applies basic site configuration."
type: 'drupal-recipe'

recipes:
  - core/recipes/basic_html_format_editor
  - core/recipes/full_html_format_editor
  - core/recipes/administrator_role
  - core/recipes/content_editor_role

install:
  - address
  - admin_toolbar
  - backup_migrate
  - better_exposed_filters
  - better_social_sharing_buttons
  - block_field
  - chosen
  - coffee
  - config_ignore
  - config_split
  - content_lock
  - csp
  - dashboard
  - editor_advanced_link
  - editoria11y
  - environment_indicator
  - facets
  - field_formatter_class
  - field_group
  - flood_control
  - focal_point
  - geolocation
  - http_cache_control
  - image_widget_crop
  - inline_entity_form
  - link_attributes
  - linkit
  - m4032404
  - mailsystem
  - masquerade
  - media_alias_display
  - media_library_edit
  - media_library_form_element
  - memcache
  - menu_admin_per_menu
  - menu_item_extras
  - menu_link_attributes
  - menu_position
  - metatag
  - navigation_extra_tools
  - paragraphs
  - paragraphs_report
  - password_policy
  - pathauto
  - quick_node_clone
  - rabbit_hole
  - redirect
  - remove_http_headers
  - restui
  - scheduler
  - schema_metatag
  - search_api
  - search_api_solr
  - seckit
  - simple_sitemap
  - stage_file_proxy
  - storybook
  - svg_image
  - tagify
  - token_filter
  - twig_tweak
  - unpublished_node_permissions
  - view_unpublished
  - views_infinite_scroll
  - webp
  - weight
